spring.application.name=ecorepair
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Seguridad JWT
app.jwt.secret=EcoRepairJwtSecretKeyForClassProject2026EcoRepairJwtSecretKey
app.jwt.expiration-ms=86400000

#Cloudinary
cloudinary.cloud-name=df6igq4wp
cloudinary.api-key=898897471764715
cloudinary.api-secret=C1um-A9rpWMZGwW1rL58EW0PfGk
cloudinary.folder=ecorepair
